---
title: "Task2"
author: "Nguyen Vi An"
date: "2025-07-01"
output: html_document
---

# 3. **Task 2**

```{r}
install.packages(c("tidyverse", "readr", "imputeTS", "naniar", "VIM", "recipes", "Hmisc", "psych", "skimr","knitr"))
```

```{r}
library(tidyverse) #include dplyr, ggplot2, ...
library(readr)
library(imputeTS) #Time-series missing data imputation
library(naniar) #help us to summarise and visualize missing data
library(dplyr)
#library(Hmisc)
library(skimr)
library(VIM) #Visualization and Imputation of Missing values: kNN(), aggr(), matrixplot()
library(recipes)
library(psych)
library(ggplot2)
```

## 3.1 Task d

### Read and Understand the Dataset

```{r}
df1 <- read_csv("../data/diabetes.csv")
print(df1)
```

### Dimension of dataset

```{r}
cat("The number of data points = ", nrow(df1), "\n")
cat("The number of variables = ", ncol(df1))
```

### Classify categorical/numerical variables

```{r}
sapply(df1, class)
```

### A descriptive analysis of each column showing the following statistical values mean, median, sd.

```{r}
describe(df1)
```

### Variance of each feature

```{r}
df1 %>%
  summarise(across(1:9, ~var(.x, na.rm = TRUE), .names = "{.col}"))
```

```{r}
df1_long <- df1 %>%
  pivot_longer(cols = 1:9, names_to = "Variable", values_to = "Value")

ggplot(df1_long, aes(x = Value)) +
  geom_histogram(bins = 30, fill = "skyblue", color = "white") +
  facet_wrap(~ Variable, scales = "free", ncol = 3) +
  labs(title = "Histogram of Each Variable",
       x = "Value", y = "Frequency") +
  theme_minimal()

ggplot(df1_long, aes(x = Variable, y = Value)) +
  geom_boxplot(fill = "tomato", outlier.color = "black", outlier.size = 1.2) +
  labs(title = "Boxplot of Each Variable", x = "", y = "Value") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

## 3.2 Task e

```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
# Bước 1: Chọn cột 2 đến 6 và chuyển 0 thành NA
df_subset <- df1 %>%
  select(2:6) %>%
  mutate(across(everything(), ~na_if(., 0)))

# Bước 2: Thay NA bằng median trong từng cột
for (colname in names(df_subset)) {
  if (any(is.na(df_subset[[colname]]))) {
    col_median <- median(df_subset[[colname]], na.rm = TRUE)
    df_subset[[colname]][is.na(df_subset[[colname]])] <- col_median
  }
  print(df_subset)
}

df_long_1 <- df_subset %>%
  pivot_longer(cols = 1:5, names_to = "Variable", values_to = "Value")

# Bước 4: Vẽ histogram cho từng cột
ggplot(df_long_1, aes(x = Value)) +
  geom_histogram(bins = 30, fill = "steelblue", color = "white") +
  facet_wrap(~ Variable, scales = "free") +
  theme_minimal() +
  labs(title = "Histogram for Each Variable",
       x = "Value",
       y = "Frequency")
```
